[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "ichnos"
version = "0.1.0"
requires-python = ">=3.10"

dependencies = [
    "astropy>=6",
    "numpy>=1.24",
    "pandas>=2.0",
    "bokeh>=2.4",
    "flask>=1.1",
    "flask-socketio>=5",
    "watchdog>=2.0"
]

[project.scripts]
ichnos = "ichnos.app:main"
